#!/usr/bin/env bash
set -o pipefail

TASK_ID="task-$(date +%Y%m%d-%H%M%S).${RANDOM}"

echo "$TASK_ID"

while true ; do
	ze < tmp/prompt 2>&1 | tee -a "tmp/${TASK_ID}"
	RESULT=$?

	if grep "DONE" <( tail -n 3 "tmp/${TASK_ID}" ) ; then
		echo "Detectamos que completou a task"
		break
	elif grep "Error: " <( tail -n 3 "tmp/${TASK_ID}" ) ; then
		echo "Detectamos um erro de execução"
	fi

	echo "Execução não concluída, retomando em 5 segundos ..."
	sleep 5
done

