#!/usr/bin/env bash
set -e

if [ -z "${SKIP_REBUILD}" ]; then
    go install ./cmd/ze || exit 1
else
    echo "[INFO] Skipping rebuild, using installed version of 'ze'"
fi

ZE_ARGS="${ZE_ARGS:- --model google/gemma-4-26B-A4B --verbose-api-calls }"

export LOG_FILE="./tmp/ze-$(date +%Y%m%d-%H%M%S).log"
script --command "ze ${ZE_ARGS}" $LOG_FILE
